#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: kinova_gripper/pose
        pose2d: kinova_gripper/ground_pose
        child_frame_id: kinova_gripper
        parent_frame_id: optitrack_origin
    '2':
        pose: human_hand/pose
        pose2d: human_hand/ground_pose
        child_frame_id: human_hand
        parent_frame_id: optitrack_origin
    '3':
        pose: object/pose
        pose2d: object/ground_pose
        child_frame_id: object
        parent_frame_id: optitrack_origin
optitrack_config:
        multicast_address: 239.255.42.99
        command_port: 1510
        data_port: 1511
